#############################################################################
# Makefile for building: qcom
# Generated by qmake (2.01a) (Qt 4.8.6) on: ?? 8? 29 09:54:19 2016
# Project:  qcom.pro
# Template: app
# Command: /usr/local/qt4.8.6-arm-none-linux-gnueabi/bin/qmake -o Makefile qcom.pro
#############################################################################

####### Compiler, tools and options

CC            = /opt/arm-2014.05/bin/arm-none-linux-gnueabi-gcc -lts
CXX           = /opt/arm-2014.05/bin/arm-none-linux-gnueabi-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/default -I. -I/usr/local/qt4.8.6-arm-none-linux-gnueabi/include/QtCore -I/usr/local/qt4.8.6-arm-none-linux-gnueabi/include/QtNetwork -I/usr/local/qt4.8.6-arm-none-linux-gnueabi/include/QtGui -I/usr/local/qt4.8.6-arm-none-linux-gnueabi/include -I. -I.
LINK          = /opt/arm-2014.05/bin/arm-none-linux-gnueabi-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/qt4.8.6-arm-none-linux-gnueabi/lib
LIBS          = $(SUBLIBS)  -L/usr/local/qt4.8.6-arm-none-linux-gnueabi//lib -lQtGui -L/usr/local/arm-linux/tslib1.4-none/lib -L/usr/local/qt4.8.6-arm-none-linux-gnueabi//lib -lQtNetwork -lQtCore -lpthread 
AR            = /opt/arm-2014.05/bin/arm-none-linux-gnueabi-ar cqs
RANLIB        = 
QMAKE         = /usr/local/qt4.8.6-arm-none-linux-gnueabi/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = /opt/arm-2014.05/bin/arm-none-linux-gnueabi-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		qextserial/qextserialport.cpp \
		qextserial/qextserialport_unix.cpp moc_mainwindow.cpp \
		qrc_images.cpp
OBJECTS       = main.o \
		mainwindow.o \
		qextserialport.o \
		qextserialport_unix.o \
		moc_mainwindow.o \
		qrc_images.o
DIST          = /usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/unix.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/linux.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/gcc-base.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/g++-base.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/g++-unix.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/qws.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/qconfig.pri \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/qt_functions.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/qt_config.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/default_pre.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/release.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/default_post.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/shared.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/warn_on.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/qt.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/unix/thread.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/moc.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/resources.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/uic.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/yacc.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/lex.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/include_source_dir.prf \
		qcom.pro
QMAKE_TARGET  = qcom
DESTDIR       = 
TARGET        = qcom

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qcom.pro  /usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/default/qmake.conf /usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/unix.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/linux.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/gcc-base.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/g++-base.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/g++-unix.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/qws.conf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/qconfig.pri \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/qt_functions.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/qt_config.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/default_pre.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/release.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/default_post.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/shared.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/warn_on.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/qt.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/unix/thread.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/moc.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/resources.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/uic.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/yacc.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/lex.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/include_source_dir.prf \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/lib/libQtGui.prl \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/lib/libQtNetwork.prl \
		/usr/local/qt4.8.6-arm-none-linux-gnueabi/lib/libQtCore.prl
	$(QMAKE) -o Makefile qcom.pro
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/unix.conf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/linux.conf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/gcc-base.conf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/g++-base.conf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/g++-unix.conf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/common/qws.conf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/qconfig.pri:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/qt_functions.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/qt_config.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/exclusive_builds.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/default_pre.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/release.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/default_post.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/shared.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/warn_on.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/qt.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/unix/thread.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/moc.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/resources.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/uic.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/yacc.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/lex.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/mkspecs/features/include_source_dir.prf:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/lib/libQtGui.prl:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/lib/libQtNetwork.prl:
/usr/local/qt4.8.6-arm-none-linux-gnueabi/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qcom.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qcom1.0.0 || $(MKDIR) .tmp/qcom1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qcom1.0.0/ && $(COPY_FILE) --parents mainwindow.h qextserial/qextserialport_global.h qextserial/qextserialport.h .tmp/qcom1.0.0/ && $(COPY_FILE) --parents images.qrc .tmp/qcom1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp qextserial/qextserialport.cpp qextserial/qextserialport_unix.cpp .tmp/qcom1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/qcom1.0.0/ && (cd `dirname .tmp/qcom1.0.0` && $(TAR) qcom1.0.0.tar qcom1.0.0 && $(COMPRESS) qcom1.0.0.tar) && $(MOVE) `dirname .tmp/qcom1.0.0`/qcom1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qcom1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_qextserialport.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_qextserialport.cpp
moc_mainwindow.cpp: qextserial/qextserialport.h \
		qextserial/qextserialport_global.h \
		mainwindow.h
	/usr/local/qt4.8.6-arm-none-linux-gnueabi//bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_qextserialport.cpp: qextserial/qextserialport_global.h \
		qextserial/qextserialport.h
	/usr/local/qt4.8.6-arm-none-linux-gnueabi//bin/moc $(DEFINES) $(INCPATH) qextserial/qextserialport.h -o moc_qextserialport.cpp

compiler_rcc_make_all: qrc_images.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_images.cpp
qrc_images.cpp: images.qrc \
		images/mesage.png \
		images/stop.png \
		images/header.bmp \
		images/send.png \
		images/cleanport.png \
		images/write2file.png \
		images/add.png \
		images/exit.png \
		images/logo129-66.png \
		images/save.png \
		images/clearbytes.png \
		images/lcd.bmp \
		images/logo42-22.png \
		images/edit-clear.png \
		images/open.png \
		images/loadfile.png
	/usr/local/qt4.8.6-arm-none-linux-gnueabi/bin/rcc -name images images.qrc -o qrc_images.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/qt4.8.6-arm-none-linux-gnueabi/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		qextserial/qextserialport.h \
		qextserial/qextserialport_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		qextserial/qextserialport.h \
		qextserial/qextserialport_global.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

qextserialport.o: qextserial/qextserialport.cpp qextserial/qextserialport.h \
		qextserial/qextserialport_global.h \
		qextserial/qextserialport_p.h \
		moc_qextserialport.cpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport.o qextserial/qextserialport.cpp

qextserialport_unix.o: qextserial/qextserialport_unix.cpp qextserial/qextserialport.h \
		qextserial/qextserialport_global.h \
		qextserial/qextserialport_p.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qextserialport_unix.o qextserial/qextserialport_unix.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

qrc_images.o: qrc_images.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_images.o qrc_images.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

